CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TABLE organizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    description text,
    email varchar(255) NOT NULL,
    phone varchar(30) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'pending',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT organizations_status_check CHECK (status IN ('pending', 'active', 'suspended', 'deleted'))
);

CREATE UNIQUE INDEX organizations_email_lower_unique
    ON organizations (lower(email));

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint,
    name varchar(120) NOT NULL,
    email varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    role varchar(30) NOT NULL DEFAULT 'adopter',
    status varchar(20) NOT NULL DEFAULT 'pending',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_role_check CHECK (role IN ('adopter', 'organization_admin', 'admin')),
    CONSTRAINT users_status_check CHECK (status IN ('pending', 'active', 'suspended', 'deleted')),
    CONSTRAINT users_organization_fk FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX users_email_lower_unique
    ON users (lower(email));

CREATE TABLE user_verifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    type varchar(30) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'pending',
    value_hash varchar(255),
    provider_reference varchar(255),
    verified_at timestamptz,
    reviewed_by bigint,
    rejection_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT user_verifications_type_check CHECK (type IN ('email', 'whatsapp', 'identity_document')),
    CONSTRAINT user_verifications_status_check CHECK (status IN ('pending', 'verified', 'rejected', 'expired')),
    CONSTRAINT user_verifications_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT user_verifications_reviewed_by_fk FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX user_verifications_active_unique
    ON user_verifications (user_id, type)
    WHERE status IN ('pending', 'verified');

CREATE TABLE pets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    name varchar(120) NOT NULL,
    description text NOT NULL,
    animal_type varchar(30) NOT NULL,
    breed varchar(80) NOT NULL,
    gender varchar(10) NOT NULL DEFAULT 'unknown',
    birth_date date,
    size varchar(20) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'available',
    city varchar(120) NOT NULL,
    state char(2) NOT NULL,
    latitude numeric(9,6),
    longitude numeric(9,6),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pets_gender_check CHECK (gender IN ('male', 'female', 'unknown')),
    CONSTRAINT pets_size_check CHECK (size IN ('small', 'medium', 'large', 'extra_large')),
    CONSTRAINT pets_status_check CHECK (status IN ('available', 'reserved', 'adopted', 'archived', 'inactive')),
    CONSTRAINT pets_latitude_check CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT pets_longitude_check CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT pets_organization_fk FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT
);

CREATE INDEX pets_organization_id_idx
    ON pets (organization_id);

CREATE INDEX pets_status_idx
    ON pets (status);

CREATE TABLE pet_photos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id bigint NOT NULL,
    path varchar(255) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pet_photos_pet_fk FOREIGN KEY (pet_id) REFERENCES pets (id) ON DELETE CASCADE,
    CONSTRAINT pet_photos_sort_order_check CHECK (sort_order >= 0)
);

CREATE INDEX pet_photos_pet_id_idx
    ON pet_photos (pet_id);

CREATE TABLE swipes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    pet_id bigint NOT NULL,
    action varchar(10) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT swipes_action_check CHECK (action IN ('like', 'pass')),
    CONSTRAINT swipes_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT swipes_pet_fk FOREIGN KEY (pet_id) REFERENCES pets (id) ON DELETE RESTRICT,
    CONSTRAINT swipes_user_pet_unique UNIQUE (user_id, pet_id)
);

CREATE INDEX swipes_user_id_idx
    ON swipes (user_id);

CREATE INDEX swipes_pet_id_idx
    ON swipes (pet_id);

CREATE TABLE favorites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    pet_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT favorites_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT favorites_pet_fk FOREIGN KEY (pet_id) REFERENCES pets (id) ON DELETE RESTRICT,
    CONSTRAINT favorites_user_pet_unique UNIQUE (user_id, pet_id)
);

CREATE INDEX favorites_user_id_idx
    ON favorites (user_id);

CREATE INDEX favorites_pet_id_idx
    ON favorites (pet_id);

CREATE TABLE matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    pet_id bigint NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT matches_status_check CHECK (status IN ('active', 'archived')),
    CONSTRAINT matches_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT matches_pet_fk FOREIGN KEY (pet_id) REFERENCES pets (id) ON DELETE RESTRICT,
    CONSTRAINT matches_user_pet_unique UNIQUE (user_id, pet_id)
);

CREATE INDEX matches_user_id_idx
    ON matches (user_id);

CREATE INDEX matches_pet_id_idx
    ON matches (pet_id);

CREATE TABLE adoption_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    pet_id bigint NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'pending',
    message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT adoption_requests_status_check CHECK (status IN ('pending', 'approved', 'rejected', 'withdrawn')),
    CONSTRAINT adoption_requests_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT adoption_requests_pet_fk FOREIGN KEY (pet_id) REFERENCES pets (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX adoption_requests_active_unique
    ON adoption_requests (user_id, pet_id)
    WHERE status IN ('pending', 'approved');

CREATE INDEX adoption_requests_user_id_idx
    ON adoption_requests (user_id);

CREATE INDEX adoption_requests_pet_id_idx
    ON adoption_requests (pet_id);

CREATE TRIGGER organizations_set_updated_at
BEFORE UPDATE ON organizations
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER user_verifications_set_updated_at
BEFORE UPDATE ON user_verifications
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER pets_set_updated_at
BEFORE UPDATE ON pets
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER adoption_requests_set_updated_at
BEFORE UPDATE ON adoption_requests
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
