<?php

declare(strict_types=1);

namespace PetMatch\Infrastructure\Database;

use PDO;
use RuntimeException;

final class MigrationExecutor
{
    public function __construct(
        private readonly PDO $pdo,
        private readonly string $migrationsPath,
    ) {
    }

    public function migrate(): array
    {
        $this->ensureSchemaTableExists();

        $appliedMigrations = $this->getAppliedMigrations();
        $pendingMigrations = $this->getPendingMigrations($appliedMigrations);

        $appliedNow = [];

        foreach ($pendingMigrations as $migration) {
            $this->pdo->beginTransaction();

            try {
                $this->pdo->exec($migration['sql']);
                $this->markAsApplied($migration['name']);
                $this->pdo->commit();
                $appliedNow[] = $migration['name'];
            } catch (\Throwable $throwable) {
                if ($this->pdo->inTransaction()) {
                    $this->pdo->rollBack();
                }

                throw new RuntimeException(
                    sprintf('Failed to apply migration %s: %s', $migration['name'], $throwable->getMessage()),
                    previous: $throwable
                );
            }
        }

        return $appliedNow;
    }

    private function ensureSchemaTableExists(): void
    {
        $this->pdo->exec(
            'CREATE TABLE IF NOT EXISTS schema_migrations (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                migration_name varchar(255) NOT NULL UNIQUE,
                applied_at timestamptz NOT NULL DEFAULT now()
            )'
        );
    }

    private function getAppliedMigrations(): array
    {
        $statement = $this->pdo->query('SELECT migration_name FROM schema_migrations ORDER BY migration_name ASC');

        return $statement->fetchAll(PDO::FETCH_COLUMN) ?: [];
    }

    private function getPendingMigrations(array $appliedMigrations): array
    {
        if (!is_dir($this->migrationsPath)) {
            throw new RuntimeException(sprintf('Migrations directory not found: %s', $this->migrationsPath));
        }

        $files = glob($this->migrationsPath . DIRECTORY_SEPARATOR . '*.up.sql') ?: [];
        sort($files, SORT_STRING);

        $pendingMigrations = [];

        foreach ($files as $file) {
            $name = basename($file, '.up.sql');

            if (in_array($name, $appliedMigrations, true)) {
                continue;
            }

            $sql = file_get_contents($file);

            if ($sql === false || trim($sql) === '') {
                throw new RuntimeException(sprintf('Migration file is empty or unreadable: %s', $file));
            }

            $pendingMigrations[] = [
                'name' => $name,
                'sql' => $sql,
            ];
        }

        return $pendingMigrations;
    }

    private function markAsApplied(string $migrationName): void
    {
        $statement = $this->pdo->prepare('INSERT INTO schema_migrations (migration_name) VALUES (:migration_name)');
        $statement->execute([
            'migration_name' => $migrationName,
        ]);
    }
}
